/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSharedRouteImport } from './routes/app.shared'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCheckinsRouteImport } from './routes/app.checkins'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppGoalsIndexRouteImport } from './routes/app.goals.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppGoalsNewRouteImport } from './routes/app.goals.new'
import { Route as AppGoalsIdRouteImport } from './routes/app.goals.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSharedKpisRouteImport } from './routes/app.admin.shared-kpis'
import { Route as AppAdminEscalationsRouteImport } from './routes/app.admin.escalations'
import { Route as AppAdminDepartmentsRouteImport } from './routes/app.admin.departments'
import { Route as AppAdminCyclesRouteImport } from './routes/app.admin.cycles'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedRoute = AppSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinsRoute = AppCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsNewRoute = AppGoalsNewRouteImport.update({
  id: '/goals/new',
  path: '/goals/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIdRoute = AppGoalsIdRouteImport.update({
  id: '/goals/$id',
  path: '/goals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSharedKpisRoute = AppAdminSharedKpisRouteImport.update({
  id: '/admin/shared-kpis',
  path: '/admin/shared-kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEscalationsRoute = AppAdminEscalationsRouteImport.update({
  id: '/admin/escalations',
  path: '/admin/escalations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepartmentsRoute = AppAdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCyclesRoute = AppAdminCyclesRouteImport.update({
  id: '/admin/cycles',
  path: '/admin/cycles',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/checkins': typeof AppCheckinsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shared': typeof AppSharedRoute
  '/app/team': typeof AppTeamRoute
  '/app/admin/cycles': typeof AppAdminCyclesRoute
  '/app/admin/departments': typeof AppAdminDepartmentsRoute
  '/app/admin/escalations': typeof AppAdminEscalationsRoute
  '/app/admin/shared-kpis': typeof AppAdminSharedKpisRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/goals/$id': typeof AppGoalsIdRoute
  '/app/goals/new': typeof AppGoalsNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/checkins': typeof AppCheckinsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shared': typeof AppSharedRoute
  '/app/team': typeof AppTeamRoute
  '/app/admin/cycles': typeof AppAdminCyclesRoute
  '/app/admin/departments': typeof AppAdminDepartmentsRoute
  '/app/admin/escalations': typeof AppAdminEscalationsRoute
  '/app/admin/shared-kpis': typeof AppAdminSharedKpisRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/goals/$id': typeof AppGoalsIdRoute
  '/app/goals/new': typeof AppGoalsNewRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/goals': typeof AppGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/checkins': typeof AppCheckinsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shared': typeof AppSharedRoute
  '/app/team': typeof AppTeamRoute
  '/app/admin/cycles': typeof AppAdminCyclesRoute
  '/app/admin/departments': typeof AppAdminDepartmentsRoute
  '/app/admin/escalations': typeof AppAdminEscalationsRoute
  '/app/admin/shared-kpis': typeof AppAdminSharedKpisRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/goals/$id': typeof AppGoalsIdRoute
  '/app/goals/new': typeof AppGoalsNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/app/approvals'
    | '/app/audit'
    | '/app/checkins'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/shared'
    | '/app/team'
    | '/app/admin/cycles'
    | '/app/admin/departments'
    | '/app/admin/escalations'
    | '/app/admin/shared-kpis'
    | '/app/admin/users'
    | '/app/goals/$id'
    | '/app/goals/new'
    | '/app/admin/'
    | '/app/goals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/app/approvals'
    | '/app/audit'
    | '/app/checkins'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/shared'
    | '/app/team'
    | '/app/admin/cycles'
    | '/app/admin/departments'
    | '/app/admin/escalations'
    | '/app/admin/shared-kpis'
    | '/app/admin/users'
    | '/app/goals/$id'
    | '/app/goals/new'
    | '/app/admin'
    | '/app/goals'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/app/approvals'
    | '/app/audit'
    | '/app/checkins'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/shared'
    | '/app/team'
    | '/app/admin/cycles'
    | '/app/admin/departments'
    | '/app/admin/escalations'
    | '/app/admin/shared-kpis'
    | '/app/admin/users'
    | '/app/goals/$id'
    | '/app/goals/new'
    | '/app/admin/'
    | '/app/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shared': {
      id: '/app/shared'
      path: '/shared'
      fullPath: '/app/shared'
      preLoaderRoute: typeof AppSharedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkins': {
      id: '/app/checkins'
      path: '/checkins'
      fullPath: '/app/checkins'
      preLoaderRoute: typeof AppCheckinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals/': {
      id: '/app/goals/'
      path: '/goals'
      fullPath: '/app/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals/new': {
      id: '/app/goals/new'
      path: '/goals/new'
      fullPath: '/app/goals/new'
      preLoaderRoute: typeof AppGoalsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals/$id': {
      id: '/app/goals/$id'
      path: '/goals/$id'
      fullPath: '/app/goals/$id'
      preLoaderRoute: typeof AppGoalsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/shared-kpis': {
      id: '/app/admin/shared-kpis'
      path: '/admin/shared-kpis'
      fullPath: '/app/admin/shared-kpis'
      preLoaderRoute: typeof AppAdminSharedKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/escalations': {
      id: '/app/admin/escalations'
      path: '/admin/escalations'
      fullPath: '/app/admin/escalations'
      preLoaderRoute: typeof AppAdminEscalationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/departments': {
      id: '/app/admin/departments'
      path: '/admin/departments'
      fullPath: '/app/admin/departments'
      preLoaderRoute: typeof AppAdminDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/cycles': {
      id: '/app/admin/cycles'
      path: '/admin/cycles'
      fullPath: '/app/admin/cycles'
      preLoaderRoute: typeof AppAdminCyclesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCheckinsRoute: typeof AppCheckinsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSharedRoute: typeof AppSharedRoute
  AppTeamRoute: typeof AppTeamRoute
  AppAdminCyclesRoute: typeof AppAdminCyclesRoute
  AppAdminDepartmentsRoute: typeof AppAdminDepartmentsRoute
  AppAdminEscalationsRoute: typeof AppAdminEscalationsRoute
  AppAdminSharedKpisRoute: typeof AppAdminSharedKpisRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppGoalsIdRoute: typeof AppGoalsIdRoute
  AppGoalsNewRoute: typeof AppGoalsNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCheckinsRoute: AppCheckinsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSharedRoute: AppSharedRoute,
  AppTeamRoute: AppTeamRoute,
  AppAdminCyclesRoute: AppAdminCyclesRoute,
  AppAdminDepartmentsRoute: AppAdminDepartmentsRoute,
  AppAdminEscalationsRoute: AppAdminEscalationsRoute,
  AppAdminSharedKpisRoute: AppAdminSharedKpisRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppGoalsIdRoute: AppGoalsIdRoute,
  AppGoalsNewRoute: AppGoalsNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
